---

#############
# DIRECTORIES
##############
result_dir:  results/        # should be kept
working_dir: temp/           # can be removed (temporary files)
keep_working_dir: TRUE # if TRUE then 'working_dir' is kept at the completion of the pipeline. if FALSE, it is deleted. 

########################################
# SAMPLE NAMES TO PACBIO SUBREADS FILES
########################################
samples: config/samples.csv


##################################################
# PACBIO BIOCONDA SUITE
# https://github.com/PacificBiosciences/pbbioconda
##################################################

# Step 1: call Circular Consensus Reads (CSS) 
ccs:
    min_accuracy: 0.99  # Minimum predicted accuracy in [0, 1]. Default of the program is 0.99

# Step 2: identify barcode and primer sequences
lima: 
    # adapters consist of forward/reverse primers and eventual barcodes (if samples are multiplexed)
    # nicknamed barcodes for simplicity and coherence with the lima tool options
    # See https://lima.how/ 
    # See also https://lima.how/barcode-design.html
    barcodes: config/barcodes.fasta 

isoseq3:
    cluster:
        min_subreads: 10 # Subread threshold for HQ/LQ split (high/low quality transcript isoforms). 



##############################
# GENOME MAPPING WITH MINIMAP2
##############################

genome:
    map_to_genome: True                               # 'True' or 'False' switch to FALSE if you want to avoid genome mapping
    genome_fasta_ref: "Stuberosum_686_v6.1_chr01.fa"  # Genome reference in FASTA format






